### ISSUE TITLE
Is it possible to trim 2 languages instead of 1?

### ISSUE THREAD

**Issue by duongttr** [asahi417/lm-vocab-trimmer#2]
Hi,

I wonder if it is possible to trim 2 languages in a single model from multilingual model?

**Comment by asahi417** [comment]
In theory, this is possible, but this library doesn't support the functionality at the moment.

When we select the tokens to keep in the vocabulary of a multilingual LM, we choose the top-N tokens based on the frequency, and this token-frequency is computed over a language specific corpus (eg. [mC4](https://huggingface.co/datasets/vocabtrimmer/mc4_validation) as default). This means if we want to keep tokens from two languages, we can select top-N tokens from the frequency from language A and language B. Technically, this is what we need to implement to enable trimming tokens for two languages.

I cannot promise but I would try to add an option to choose multiple languages in the API of the library.

**Comment by duongttr** [comment]
Thank you for considering adding the option to choose multiple languages in the library's API. It's great to hear that you're open to exploring this possibility. Providing support for multiple languages would be a valuable feature for users working with multilingual models. We appreciate your efforts and look forward to any updates or enhancements to the library in the future.

**Comment by Respaired** [comment]
yeah this is much needed. especially for translation tasks
